name: Run Robot Framework Tests

on:
  push:
    branches:
      - TriggerEmail

jobs:
  test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Robot Framework tests
        id: test-step
        run: |
          robot -d results ./TestCases/Files || echo "Tests failed"

      - name: Upload Robot test reports
        if: always()
        uses: actions/upload-artifact@v3.1.3  # <-- use fixed version
        with:
          name: robot-results
          path: results/

      - name: Check Robot test result
        id: check-result
        run: |
          if [ -f results/output.xml ]; then
            echo "status=pass" >> $GITHUB_OUTPUT
          else
            echo "status=fail" >> $GITHUB_OUTPUT
          fi
